all: rat_tcpclient rat_tcpserver

rat_tcpclient: rat_tcpclient.cpp util.cpp
	g++ rat_tcpclient.cpp util.cpp -o rat_tcpclient

rat_tcpserver: rat_tcpserver.cpp util.cpp
	g++ rat_tcpserver.cpp util.cpp -o rat_tcpserver
